server:
  port: 9999
spring:
  application:
    name: release-creator
  profiles:
    active: local
validation:
  task-number-pattern: ^TTTPLN-\d+$

resilience4j:
  ratelimiter:
    instances:
      bitbucket:
        limit-for-period: 1
        limit-refresh-period: 1s
        timeout-duration: 10s

integrations:
  bitbucket:
    base-url: http://localhost:7990
    username: ${BITBUCKET_USERNAME:}
    token: ${BITBUCKET_TOKEN:}
    project-key: MYPROJ
    develop-branch: develop
    master-branch: master
  teamcity:
    base-url: http://localhost:8111
    token: ${TEAMCITY_TOKEN:}
    poll-interval: 60s
    wait-timeout: 5h
  excluded-repositories:
    - "service1"
    - "service2"
  build-name-exceptions:
    release-production-exceptions:
      service1: ser1_ReleaseProduction
      service2: service_2_ReleaseProduction
    just-build-exceptions:
      service1: ser1_Build
      service2: service_2_Build
    tst1-deploy-exceptions:
      service1: ser1_DeployTST1
      service2: service_2_DeployTST1

logging:
  level:
    root: INFO
    com.dtim.releasecreator: INFO
