spring:
  application:
    name: releasecreator

server:
  port: ${SERVER_PORT:8080}

integrations:
  bitbucket:
    base-url: http://localhost:7990
    username: ${BITBUCKET_USERNAME:}
    token: ${BITBUCKET_TOKEN:}
    project-key: MYPROJ
    develop-branch: develop
    master-branch: master
  teamcity:
    base-url: http://localhost:8111
    token: ${TEAMCITY_TOKEN:}
    poll-interval: 60s
    wait-timeout: 5h
  excluded-repositories:
    - "service1"
    - "service2"

logging:
  level:
    root: INFO
    com.dtim.releasecreator: INFO
